# Tensorflow2.0 小练习

In [2]:
import tensorflow as tf
import numpy as np

## 实现softmax函数

In [3]:
def softmax(x):
    ##########
    '''实现softmax函数，只要求对最后一维归一化，
    不允许用tf自带的softmax函数'''
    ##########
    exp_x = np.exp(x)  
    prob_x = exp_x / np.sum(exp_x, axis=-1, keepdims=True)
    print(prob_x)
    return prob_x

test_data = np.random.normal(size=[10, 5])
(softmax(test_data) - tf.nn.softmax(test_data, axis=-1).numpy())**2 <0.0001



[[0.05763663 0.11501876 0.11480854 0.24085063 0.47168544]
 [0.07064363 0.26178972 0.26324515 0.32891719 0.0754043 ]
 [0.18356924 0.22231097 0.07674183 0.23442906 0.28294891]
 [0.54275745 0.18352997 0.07575646 0.11422381 0.08373232]
 [0.12858453 0.33837557 0.0591574  0.33138253 0.14249998]
 [0.0167127  0.01358114 0.66848779 0.08254869 0.21866968]
 [0.25842316 0.19001957 0.12612167 0.16810953 0.25732607]
 [0.26344314 0.31928169 0.09769065 0.1219043  0.19768022]
 [0.079048   0.45791952 0.03367734 0.29216345 0.13719169]
 [0.07087097 0.03926406 0.75577718 0.02351924 0.11056855]]


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现sigmoid函数

In [4]:
def sigmoid(x):
    ##########
    '''实现sigmoid函数， 不允许用tf自带的sigmoid函数'''
    ##########
    prob_x= 1.0 / (1.0 + np.exp(-x))
    return prob_x

test_data = np.random.normal(size=[10, 5])
(sigmoid(test_data) - tf.nn.sigmoid(test_data).numpy())**2 < 0.0001

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

## 实现 softmax 交叉熵loss函数

In [3]:
def softmax_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    loss=-np.sum(label * np.log(prob + 1e-12)) / label.shape[0]
    return loss

test_data = np.random.normal(size=[10, 5])
prob = tf.nn.softmax(test_data)
label = np.zeros_like(test_data)
label[np.arange(10), np.random.randint(0, 5, size=10)]=1.

((tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(label, test_data))
  - softmax_ce(prob, label))**2 < 0.0001).numpy()

np.True_

## 实现 sigmoid 交叉熵loss函数

In [7]:
def sigmoid_ce(x, label):
    ##########
    '''实现 softmax 交叉熵loss函数， 不允许用tf自带的softmax_cross_entropy函数'''
    ##########
    epsilon = 1e-12
    prob = np.clip(x, epsilon, 1 - epsilon)  # 将概率限制在 [epsilon, 1 - epsilon] 范围内
    loss = -np.mean(label * np.log(prob) + (1 - label) * np.log(1 - prob))
    return loss

test_data = np.random.normal(size=[10])
prob = tf.nn.sigmoid(test_data)
label = np.random.randint(0, 2, 10).astype(test_data.dtype)
print (label)

((tf.reduce_mean(tf.nn.sigmoid_cross_entropy_with_logits(label, test_data))- sigmoid_ce(prob, label))**2 < 0.0001).numpy()


[1. 1. 1. 0. 1. 0. 0. 1. 0. 0.]


np.True_